In [2]:
import pandas as pd
df = pd.read_csv("elctricity consumption.csv")
print(df)

         date  units and measurement  house number  application usage hours  \
0   5/19/2001                      2            34                        3
1   5/20/2001                      3            35                        4
2   5/21/2001                      4            36                        5
3   5/22/2001                      5            37                        6
4   5/23/2001                      6            38                        7
5   5/24/2001                      7            39                        8
6   5/25/2001                      8            40                        9
7   5/26/2001                      9            41                       10
8   5/27/2001                     10            42                       11
9   5/28/2001                     11            43                       12
10  5/29/2001                     12            44                       13
11  5/30/2001                     13            45                       14
12  5/31/2001                     14            46                       15
13   6/1/2001                     15            47                       16
14   6/2/2001                     16            48                       17
15   6/3/2001                     17            49                       18
16   6/4/2001                     18            50                       19
17   6/5/2001                     19            51                       20
18   6/6/2001                     20            52                       21
19   6/7/2001                     21            53                       22
20   6/8/2001                     22            54                       23

    monthly bill
0           1000
1           1000
2           1000
3           1000
4           1000
5           1400
6           1400
7           1400
8           1400
9           1400
10          1400
11          1400
12          1400
13          2000
14          2000
15          2000
16          2000
17          2000
18          2000
19          2000
20          2000

In [3]:
import pandas as pd
df = pd.read_csv("elctricity consumption.csv")
df.describe()

,units and measurement,house number,application usage hours,monthly bill
count,21.000000,21.000000,21.000000,21.000000
mean,12.000000,44.000000,13.000000,1533.333333
std,6.204837,6.204837,6.204837,406.612018
min,2.000000,34.000000,3.000000,1000.000000
25%,7.000000,39.000000,8.000000,1400.000000
50%,12.000000,44.000000,13.000000,1400.000000
75%,17.000000,49.000000,18.000000,2000.000000
max,22.000000,54.000000,23.000000,2000.000000

In [13]:
import pandas as pd 
df = pd.read_csv("elctricity consumption.csv")
print(df.columns)

Index(['date', 'units and measurement', 'house number',
       'application usage hours', 'monthly bill'],
      dtype='str')

In [15]:
import pandas as pd 
df = pd.read_csv("elctricity consumption.csv")
mean_bill = df["monthly bill"].mean()
print(mean_bill)

1533.3333333333333

In [16]:
import pandas as pd 
df = pd.read_csv("elctricity consumption.csv")
df.head()

,date,units and measurement,house number,application usage hours,monthly bill
0,5/19/2001,2,34,3,1000
1,5/20/2001,3,35,4,1000
2,5/21/2001,4,36,5,1000
3,5/22/2001,5,37,6,1000
4,5/23/2001,6,38,7,1000

In [18]:
import pandas as pd 
df = pd.read_csv("elctricity consumption.csv")
print(df["units and measurement"].max())

22